services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - "./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources"
      - "./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards"
    environment:
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
  
  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    ports:
      - "8086:8086"
    env_file:
      - .env
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2

  # py-backend:
  #   container_name: py-backend
  #   build: ./backend
  #   env_file:
  #     - .env
  #   depends_on:
  #     - influxdb2

volumes:
  influxdb2-data:
  influxdb2-config:
