services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - "./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources"
      - "./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards"
