version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

  # Once everything’s up, creates 20 the topics with:
  # for i in {1..20}; do docker exec -it kafka kafka-topics --create --topic sensor$i --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1; done

  # Then check the topics created:
  # docker exec -it kafka kafka-topics --list --bootstrap-server localhost:9092
